FROM node:21-alpine

WORKDIR /app

COPY ./package*.json .
RUN npm install

COPY . .

EXPOSE 8000
CMD npm uninstall bcrypt @types/bcrypt \
&& npm install -D @types/bcrypt \
&& npm install bcrypt \ 
&& npm run build \
&& npm run start:prod