FROM node:21-alpine

WORKDIR /app

COPY ./package*.json .
RUN npm install

COPY . .

EXPOSE 3001
CMD npm uninstall bcrypt @types/bcrypt \
&& npm install -D @types/bcrypt \
&& npm install bcrypt \
&& npm run start:dev