FROM node:21-alpine

WORKDIR /app

COPY ./package*.json .
RUN npm install

COPY . .
RUN npm run build 

EXPOSE 8000
CMD npm uninstall bcrypt @types/bcrypt \
&& npm install -D @types/bcrypt \
&& npm install bcrypt \ 
&& npm run start:prod