export enum ApplicationRoutes {
  Root = '/',
  Any = '*',
  SignIn = '/sign-in',
  SignUp = '/sign-up',
  AccountCompletion = '/account-completion',
  Home = '/home',
  Dashboard = '/dashboard',
  Profile = '/profile',
  Users = '/users',
  UserDetails = '/users/:id',
  UserCreate = '/users/create',
  UserEdit = '/users/:id/edit',
  Posts = '/posts',
  PostDetails = '/posts/:id',
  PostCreate = '/posts/create',
  PostEdit = '/posts/:id/edit',
  Chats = '/chats',
  ChatDetails = '/chats/:id',
}

export const ProtectedRoutes: ApplicationRoutes[] = [
  ApplicationRoutes.Home,
  ApplicationRoutes.Profile,
  ApplicationRoutes.PostCreate,
  ApplicationRoutes.PostEdit,
  ApplicationRoutes.UserCreate,
  ApplicationRoutes.UserEdit,
  ApplicationRoutes.Chats,
  ApplicationRoutes.ChatDetails,
];
