export const getFileExtension = (file: Express.Multer.File) =>
  /[.]/.exec(file.originalname) ? /[^.]+$/.exec(file.originalname) : '';

export const getCloudinaryResourceType = (file: Express.Multer.File) => {
  const resourceTypes: { [key: string]: string[] } = {
    image: [
      'application/postscript',
      'image/avif',
      'image/gif',
      'image/png',
      'image/webp',
      'image/bmp',
      'application/vnd.3gpp.pic-bw-large',
      'application/vnd.3gpp.pic-bw-small',
      'application/vnd.3gpp.pic-bw-var',
      'image/vnd.djvu',
      'image/x-adobe-dng',
      'application/fbx',
      'image/flif',
      'model/gltf-binary',
      'model/gltf+json',
      'image/heic',
      'image/x-icon',
      'application/x-indesign',
      'image/jpeg',
      'image/jp2',
      'image/vnd.ms-photo',
      'image/jxr',
      'image/jxl',
      'model/obj',
      'application/obj',
      'application/pdf',
      'image/vnd.adobe.photoshop',
      'image/x-sony-arw',
      'image/x-canon-cr2',
      'image/svg+xml',
      'image/x-tga',
      'image/x-targa',
      'image/tga',
      'image/tiff',
      'model/vnd.usdz+zip',
    ],
    video: [
      'video/3gpp2',
      'video/3gpp',
      'video/x-msvideo',
      'video/x-flv',
      'video/x-ms-wmv',
      'video/webm',
      'video/quicktime',
      'video/mp4',
      'video/mpeg',
      'video/ogg',
      'video/x-matroska',
      'application/mxf',
      'audio/aac',
      'audio/mp4',
      'audio/mpeg',
      'audio/m4a',
      'audio/aiff',
      'audio/mp4a-latm',
      'audio/ogg',
      'audio/AMR',
      'audio/flac',
      'audio/opus',
      'audio/vnd.wave',
      'audio/wav',
      'audio/wave',
      'audio/x-pn-wav',
      'audio/x-wav',
    ],
  };

  return (
    Object.keys(resourceTypes).find(key => resourceTypes[key].includes(file.mimetype)) ?? 'raw'
  );
};
